version: 2.1
orbs:
  node: circleci/node@3.0.0

defaults: &defaults
  working_directory: ~/hub-react
  executor:
    name: node/default

jobs:
  test:
    << : *defaults
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests via yarn
      - persist_to_workspace:
        root: ~/hub-react
        paths: .

  build:
    << : *defaults
    steps:
      - run:
          command: yarn build
          name: Build ts to lib/ via yarn
      - persist_to_workspace:
        root: ~/hub-react
        paths: .

  deploy:
    << : *defaults
    steps:
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/hub-react/.npmrc
      - run:
          name: Publish package
          command: npm publish --dry-run


workflows:
  test_my_app:
    jobs:
      - test

  test_deploy:
    jobs:
      - build
