version: 2.1
orbs:
  node: circleci/node@3.0.0

defaults: &defaults
  working_directory: ~/hub-react
  executor:
    name: node/default

test_steps: &test_steps
  steps:
      - checkout
      - node/install-packages:
          app-dir: ~/hub-react
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests via yarn
      - persist_to_workspace:
          root: ~/hub-react
          paths: .

jobs:
  test:
    << : *defaults
    << : *test_steps

  build_and_deploy:
    << : *defaults
    << : *test_steps
    steps:
      - run:
          command: yarn build
          name: Compile TS to JS
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/hub-react/.npmrc
      - run:
          name: Publish package
          command: npm publish --dry-run


workflows:
  test_my_app:
    jobs:
      - test

  test_deploy:
    jobs:
      - build_and_deploy