version: 2.1
orbs:
  node: circleci/node@5.0.0

commands:
  test_steps:
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run unit tests (Jest)
          command: yarn test
      - run:
          name: Check formatting
          command: yarn format-check

  build_steps:
    steps:
      - run:
          name: Compile TS to JS
          command: yarn build
      - run:
          name: Run build integration test
          command: ./build_integration_test.sh
jobs:
  test:
    executor:
      name: node/default
    steps:
      - test_steps
      - build_steps

  test_build_and_publish:
    executor:
      name: node/default
    steps:
      - test_steps
      - build_steps
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: .circleci/publish.sh

workflows:
  test_library:
    jobs:
      - test:
          filters:
            tags:
              ignore: /^v.*/

  publish:
    jobs:
      - test_build_and_publish:
          context:
            - npm-automation
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
