version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests via yarn

  build:
    executor:
      name: node/default
    steps:
      - run:
          command: yarn build
          name: Build ts to lib/ via yarn

  deploy:
    executor:
      name: node/default
    steps:
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish --dry-run


workflows:
  test_my_app:
    jobs:
      - test

  test_deploy:
    jobs:
      - test
      - deploy:
        requires:
          -test
